#!/usr/bin/env bash
#installs nginx and redirects 
sudo apt-get -y update
sudo apt-get -y install nginx
file1=/usr/share/nginx/html/index.html
file=/etc/nginx/sites-available/default
sudo bash -c "echo 'Hello World!' > $file1"
service nginx start
phrase="301 Moved Permanently"
sudo sed -i "30i $phrase" $file
sudo service nginx restart
