#!/usr/bin/env bash
#install ngix and put holberton inside
redir="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
sudo apt-get update
sudo apt-get install nginx -y
echo "301 Moved Permanently" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i $redir" /etc/nginx/sites-available/default
sudo service nginx start
